name: izi_frontend
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  flutter_dotenv: ^5.2.1
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  flutter_login: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  fl_chart: ^0.63.0

flutter:
  uses-material-design: true
  assets:
    - .env
